//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfs.Web.OT_QUESTION {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblQS_ID;
		protected global::System.Web.UI.WebControls.TextBox txtQS_TYPE;
		protected global::System.Web.UI.WebControls.TextBox txtQS_EID;
		protected global::System.Web.UI.WebControls.TextBox txtQS_CONTENT;
		protected global::System.Web.UI.WebControls.TextBox txtQS_CHOICE_A;
		protected global::System.Web.UI.WebControls.TextBox txtQS_CHOICE_B;
		protected global::System.Web.UI.WebControls.TextBox txtQS_CHOICE_C;
		protected global::System.Web.UI.WebControls.TextBox txtQS_CHOICE_D;
		protected global::System.Web.UI.WebControls.TextBox txtQS_CHOICE_COR;
		protected global::System.Web.UI.WebControls.TextBox txtQS_COR_EXPLAINATION;
		protected global::System.Web.UI.WebControls.TextBox txtQS_DELFLAG;
		protected global::System.Web.UI.WebControls.TextBox txtQS_HARD;
		protected global::System.Web.UI.WebControls.TextBox txtQS_CTIME;
		protected global::System.Web.UI.WebControls.TextBox txtQS_TID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
