//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfs.Web.OT_QUESTION {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblQS_ID;
	protected global::System.Web.UI.WebControls.Label lblQS_TYPE;
	protected global::System.Web.UI.WebControls.Label lblQS_EID;
	protected global::System.Web.UI.WebControls.Label lblQS_CONTENT;
	protected global::System.Web.UI.WebControls.Label lblQS_CHOICE_A;
	protected global::System.Web.UI.WebControls.Label lblQS_CHOICE_B;
	protected global::System.Web.UI.WebControls.Label lblQS_CHOICE_C;
	protected global::System.Web.UI.WebControls.Label lblQS_CHOICE_D;
	protected global::System.Web.UI.WebControls.Label lblQS_CHOICE_COR;
	protected global::System.Web.UI.WebControls.Label lblQS_COR_EXPLAINATION;
	protected global::System.Web.UI.WebControls.Label lblQS_DELFLAG;
	protected global::System.Web.UI.WebControls.Label lblQS_HARD;
	protected global::System.Web.UI.WebControls.Label lblQS_CTIME;
	protected global::System.Web.UI.WebControls.Label lblQS_TID;


       
    }
}
