//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfs.Web.OT_SESSION {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblSE_ID;
		protected global::System.Web.UI.WebControls.TextBox txtSE_TID;
		protected global::System.Web.UI.WebControls.TextBox txtSE_CTIME;
		protected global::System.Web.UI.WebControls.TextBox txtSE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtSE_CONTENT;
		protected global::System.Web.UI.WebControls.TextBox txtSE_TTIME;
		protected global::System.Web.UI.WebControls.TextBox txtSE_DTIME;
		protected global::System.Web.UI.WebControls.TextBox txtSE_DELFLAG;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
