//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfs.Web.OT_SESSION {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblSE_ID;
	protected global::System.Web.UI.WebControls.Label lblSE_TID;
	protected global::System.Web.UI.WebControls.Label lblSE_CTIME;
	protected global::System.Web.UI.WebControls.Label lblSE_NAME;
	protected global::System.Web.UI.WebControls.Label lblSE_CONTENT;
	protected global::System.Web.UI.WebControls.Label lblSE_TTIME;
	protected global::System.Web.UI.WebControls.Label lblSE_DTIME;
	protected global::System.Web.UI.WebControls.Label lblSE_DELFLAG;


       
    }
}
