//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfs.Web.OT_ESSAY {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblES_ID;
		protected global::System.Web.UI.WebControls.TextBox txtES_TYPE;
		protected global::System.Web.UI.WebControls.TextBox txtES_TITLE;
		protected global::System.Web.UI.WebControls.TextBox txtES_CONTENT;
		protected global::System.Web.UI.WebControls.TextBox txtES_HARD;
		protected global::System.Web.UI.WebControls.TextBox txtES_DELFLAG;
		protected global::System.Web.UI.WebControls.TextBox txtES_CTIME;
		protected global::System.Web.UI.WebControls.TextBox txtES_TID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
