//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfs.Web.OT_ESSAY {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblES_ID;
	protected global::System.Web.UI.WebControls.Label lblES_TYPE;
	protected global::System.Web.UI.WebControls.Label lblES_TITLE;
	protected global::System.Web.UI.WebControls.Label lblES_CONTENT;
	protected global::System.Web.UI.WebControls.Label lblES_HARD;
	protected global::System.Web.UI.WebControls.Label lblES_DELFLAG;
	protected global::System.Web.UI.WebControls.Label lblES_CTIME;
	protected global::System.Web.UI.WebControls.Label lblES_TID;


       
    }
}
